### ISSUE TITLE
finaliseSolution not being called for codim2 fold point continuation

### ISSUE THREAD

**Issue by yhchang96** [bifurcationkit/BifurcationKit.jl#79] opened 2023-01-28 05:06 UTC
Similar to the solved issue [here](https://github.com/bifurcationkit/BifurcationKit.jl/issues/76), except now it is `finaliseSolution` that is not working in a codim2 fold point continuation. Again using the temperature model as an example:

```
using BifurcationKit, LinearAlgebra, Parameters, Setfield
const BK = BifurcationKit

Nop(x; a = 0.5, b = 0.01) = 1 + (x + a*x^2)/(1 + b*x^2)

function F_chan(x, p)
    α, β = p.α, p.β
    f = similar(x)
    n = length(x)
    f[1] = x[1] - β
    f[n] = x[n] - β
    for i=2:n-1
        f[i] = (x[i-1] - 2 * x[i] + x[i+1]) * (n-1)^2 + α * Nop(x[i], b = β)
    end
    return f
end

function finaliseSol_test(z, tau, step, contResult; kwargs...)
    println("it is working!!!")   # just to test whether it is being called
    return true
end

n = 101
sol0 = [(i-1)*(n-i)/n^2+0.1 for i=1:n]
par = (α = 3.3, β = 0.01)
prob = BifurcationProblem(F_chan, sol0, par, (@lens _.α))
optcont = ContinuationPar(dsmin = 0.01, dsmax = 0.05, ds= 0.01, pMin = 0., pMax = 4.2,
    newtonOptions = NewtonPar(maxIter = 10, tol = 1e-9), saveSolEveryStep=1, detectBifurcation=0)

br = continuation(prob, PALC(), optcont, finaliseSolution=finaliseSol_test)   # finaliseSol_test is being called

outfoldco = continuation(br, 2, (@lens _.β), optcont, finaliseSolution=finaliseSol_test)   # finaliseSol_test is not being called
```

The word `it is working!!!` is printed successfully for `br` but not for `outfoldco`.

**Comment by rveltz** [comment] 2023-01-28 06:49
> Note that the Fold continuation is slow with the default options. Indeed, the default options are tailred for ODE. pass `jacobian_ma = :minaug` to your last call to have an optimised Fold continuation.

Thank you for finding this bug. The issue is with the options `updateMinAugEveryStep` for fold continuation. For now, passing `updateMinAugEveryStep = 1` should do.

**Comment by rveltz** [comment] 2023-01-28 10:57
should be fixed on master!

**Comment by rveltz** [comment] 2023-03-06 10:26
Should we close this?

**Closed** 2023-03-06 18:43 UTC
